### ISSUE TITLE
训练cifar100的学生网络时，精确度很低，最后保持0.01

### ISSUE THREAD

**Issue by tangjialiang-jj** [huawei-noah/Data-Efficient-Model-Compression#10]
[Epoch 181/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000303]
Test Avg. Loss: 19101.246094, Accuracy: 0.010000
[Epoch 182/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000302]
Test Avg. Loss: 19077.779297, Accuracy: 0.010000
[Epoch 183/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000300]
Test Avg. Loss: 19057.632812, Accuracy: 0.010000
[Epoch 184/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000299]
Test Avg. Loss: 19041.076172, Accuracy: 0.010000
[Epoch 185/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000298]
Test Avg. Loss: 19022.105469, Accuracy: 0.010000
[Epoch 186/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000297]
Test Avg. Loss: 18999.925781, Accuracy: 0.010000
[Epoch 187/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000295]
Test Avg. Loss: 18975.453125, Accuracy: 0.010000
[Epoch 188/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000293]
Test Avg. Loss: 18949.039062, Accuracy: 0.010000
[Epoch 189/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000293]
Test Avg. Loss: 18920.974609, Accuracy: 0.010000
[Epoch 190/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000292]
Test Avg. Loss: 18893.566406, Accuracy: 0.010000
[Epoch 191/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000290]
Test Avg. Loss: 18866.751953, Accuracy: 0.010000
[Epoch 192/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000289]
Test Avg. Loss: 18838.226562, Accuracy: 0.010000
[Epoch 193/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000288]
Test Avg. Loss: 18808.751953, Accuracy: 0.010000
[Epoch 194/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000286]
Test Avg. Loss: 18779.259766, Accuracy: 0.010000
[Epoch 195/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000286]
Test Avg. Loss: 18749.382812, Accuracy: 0.010000
[Epoch 196/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000285]
Test Avg. Loss: 18719.992188, Accuracy: 0.010000
[Epoch 197/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000283]
Test Avg. Loss: 18692.478516, Accuracy: 0.010000
[Epoch 198/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000283]
Test Avg. Loss: 18664.859375, Accuracy: 0.010000
[Epoch 199/200] [loss_oh: 0.000758] [loss_ie: -0.003434] [loss_a: -0.325599] [loss_kd: 0.000281]
Test Avg. Loss: 18637.296875, Accuracy: 0.010000

**Comment by tangjialiang-jj** [comment]
再一次训练仍然这样

**Comment by tangjialiang-jj** [comment]
因为我电脑最多支持128的batchsize，所以我把batchsize设置为128，这样会影响精确度么

**Comment by HantingChen** [comment]
> 因为我电脑最多支持128的batchsize，所以我把batchsize设置为128，这样会影响精确度么
会的 最好还是用1024的batch size

**Comment by tangjialiang-jj** [comment]
> > 因为我电脑最多支持128的batchsize，所以我把batchsize设置为128，这样会影响精确度么
> > 会的 最好还是用1024的batch size

请问1024的batchsize需要多大的显存

**Comment by tangjialiang-jj** [comment]
> > 因为我电脑最多支持128的batchsize，所以我把batchsize设置为128，这样会影响精确度么
> 
> 会的 最好还是用1024的batch size

请问你训练的时候有出现多卡训练负载不均衡的问题么，我训练的时候两张卡和一张卡运行最大的batchsize几乎一样

**Comment by tangjialiang-jj** [comment]
> > > 因为我电脑最多支持128的batchsize，所以我把batchsize设置为128，这样会影响精确度么
> > 
> > 
> > 会的 最好还是用1024的batch size
> 
> 请问你训练的时候有出现多卡训练负载不均衡的问题么，我训练的时候两张卡和一张卡运行最大的batchsize几乎一样

我有个问题一直没想通，为什么batchsize要设定到这么大才能有好的效果，是因为batchsize设置的太小会受随机性影响很大么，希望作者有空能解答一下

**Comment by HantingChen** [comment]
> 
> 
> > > > 因为我电脑最多支持128的batchsize，所以我把batchsize设置为128，这样会影响精确度么
> > > 
> > > 
> > > 会的 最好还是用1024的batch size
> > 
> > 
> > 请问你训练的时候有出现多卡训练负载不均衡的问题么，我训练的时候两张卡和一张卡运行最大的batchsize几乎一样
> 
> 我有个问题一直没想通，为什么batchsize要设定到这么大才能有好的效果，是因为batchsize设置的太小会受随机性影响很大么，希望作者有空能解答一下

因为类别均衡的loss是每个batch计算的，batchsize太小无法就生成足够每个类别训练的样本。

**Comment by yixiaonaihe** [comment]
> 再一次训练仍然这样

请问下有尝试训练MNIST么，精度如何(⊙o⊙)?
