### ISSUE TITLE
Entropy in DAFL

### ISSUE THREAD

**Issue by tjdhg456** [huawei-noah/Data-Efficient-Model-Compression#19]
Hello. Thank you for your great work.

For calculating the information entropy loss in the DAFL_train.py, minus is not needed? 

Entropy = - summation (p * ln(p))

![image](https://user-images.githubusercontent.com/52290290/118983749-ba426800-b9b7-11eb-9a58-02948134f7dc.png)

**Comment by HantingChen** [comment]
See Equ. (6) in the paper: https://openaccess.thecvf.com/content_ICCV_2019/papers/Chen_Data-Free_Learning_of_Student_Networks_ICCV_2019_paper.pdf. The two minus signs come together to make a positive sign.

**Comment by tjdhg456** [comment]
Thank you for the answer!@!
