### ISSUE TITLE
Compute avg_loss wrongly

### ISSUE THREAD

**Issue by hkunzhe** [huawei-noah/Data-Efficient-Model-Compression#21]
[L199](https://github.com/huawei-noah/Data-Efficient-Model-Compression/blob/master/DAFL/DAFL-train.py#L199) `avg_loss /= len(data_test)` should be `avg_loss/=len(data_test_loader)`.
BTW, when will you open source your latest work Learning Student Networks in the Wild?

**Comment by HantingChen** [comment]
Thanks for your correction!

The code is under approval and will be released in few weeks or months.

**Comment by HantingChen** [comment]
Code is available at https://github.com/huawei-noah/Efficient-Computing/tree/master/Data-Efficient%20Model%20Compression/DFND
